=== callmeaash/xml-lab/question12/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bib">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="editor" type="xs:string" minOccurs="0"/>
                            <xs:element name="publisher" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="year" type="xs:gYear"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== callmeaash/xml-lab/question12/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="books.xslt" type="text/xsl"?>
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="books.xsd">
    <book year="1992"> 
        <title>The Economics of Technology and Content for Digital TV</title> 
        <author>Buneman</author>
        <editor>Gerbarg</editor> 
        <publisher>Kluwer Academic Publishers</publisher> 
        <price>129.95</price> 
    </book>
    <book year="2000"> 
     <title>Data on the Web</title> 
     <author>Abiteboul</author> 
     <author>Buneman</author> 
     <author>Suciu</author> 
     <publisher>Morgan Kaufmann Publishers</publisher> 
     <price> 39.95</price> 
 </book>  
</bib>
