=== callmeaash/xml-lab/question6/schools.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="schools">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="location" type="xs:string"/>
                            <xs:element name="staff" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="title" type="xs:string" minOccurs="0"/>
                                        <xs:element name="category">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="academic"/>
                                                    <xs:enumeration value="general"/>
                                                    <xs:enumeration value="technical"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="address" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="street" type="xs:string"/>
                                                    <xs:element name="postcode" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                                
                            </xs:element>
                            <xs:element name="subjects">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="code" type="xs:ID"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                    <xs:element name="capacity">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minExclusive value="6"/>
                                                                <xs:maxExclusive value="600"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="teacher" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="ref" type="xs:IDREF" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"/>
                    </xs:complexType>
                    <xs:unique name="uniqueStaffId">
                        <xs:selector xpath="staff"/>
                        <xs:field xpath="@id"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueSchoolID">
            <xs:selector xpath="school"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== callmeaash/xml-lab/question6/schools.xml
<?xml version="1.0" encoding="UTF-8"?>
<schools xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="schools.xsd">

            <school id="1">
                <name>Texas</name>
                <location>USA</location>
                <staff id="T10">
                    <name>alakh</name>
                    <category>academic</category>
                    <address>
                        <street>massac</street>
                        <postcode>20000</postcode>
                    </address>
                </staff>

                <subjects>
                    <subject>
                        <code>CACS200</code>
                        <name>Computer Science</name>
                        <description>nice</description>
                        <capacity>300</capacity>
                        <teacher ref="T10" />
                    </subject>
                </subjects>
            </school>
</schools>
