=== callmeaash/xml-lab/question5/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="dateformat">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string"/>
                                        <xs:element name="middlename" type="xs:string" minOccurs="0"/>
                                        <xs:element name="lastname" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="address" maxOccurs="2">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="permanent"/>
                                                        <xs:enumeration value="temporary"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dob">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="dateformat">
                                            <xs:attribute name="type" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="AD"/>
                                                        <xs:enumeration value="BS"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]{6,}@gmail\.com"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="phone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(98|97)\d{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="rollno" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueRoll">
            <xs:selector xpath="student"/>
            <xs:field xpath="@rollno"></xs:field>
        </xs:unique>
    </xs:element>
</xs:schema>

=== callmeaash/xml-lab/question5/students.xml
<?xml version="1.0" encoding="UTF-8"?>  
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="students.xsd">
            
            <student rollno="1">
                <name>
                    <firstname>aashish</firstname>
                    <lastname>bogati</lastname>
                </name>
                <address type="permanent">Achham</address>
                <dob type="AD">2004-02-20</dob>
                <email>aashishbogati@gmail.com</email>
                <phone>9727272727</phone>
            </student>
</students>
